// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// direct_lingam_c
std::vector<double> direct_lingam_c(arma::mat X);
RcppExport SEXP _causalXtreme_direct_lingam_c(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(direct_lingam_c(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_causalXtreme_direct_lingam_c", (DL_FUNC) &_causalXtreme_direct_lingam_c, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_causalXtreme(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
