// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// center_rows
arma::mat center_rows(const arma::mat& G);
RcppExport SEXP _causalXtreme_center_rows(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(center_rows(G));
    return rcpp_result_gen;
END_RCPP
}
// findindexc
double findindexc(const arma::mat& X, const Rcpp::IntegerVector& candidates, const Rcpp::IntegerVector& U_K);
RcppExport SEXP _causalXtreme_findindexc(SEXP XSEXP, SEXP candidatesSEXP, SEXP U_KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type U_K(U_KSEXP);
    rcpp_result_gen = Rcpp::wrap(findindexc(X, candidates, U_K));
    return rcpp_result_gen;
END_RCPP
}
// computeRc
arma::cube computeRc(const arma::mat& X, const Rcpp::IntegerVector& candidates, const Rcpp::IntegerVector& U_K, const arma::mat& M);
RcppExport SEXP _causalXtreme_computeRc(SEXP XSEXP, SEXP candidatesSEXP, SEXP U_KSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type U_K(U_KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(computeRc(X, candidates, U_K, M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_causalXtreme_center_rows", (DL_FUNC) &_causalXtreme_center_rows, 1},
    {"_causalXtreme_findindexc", (DL_FUNC) &_causalXtreme_findindexc, 3},
    {"_causalXtreme_computeRc", (DL_FUNC) &_causalXtreme_computeRc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_causalXtreme(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
