# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

direct_lingam_c <- function(X) {
    .Call(`_causalXtreme_direct_lingam_c`, X)
}

