# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

center_rows <- function(G) {
    .Call(`_causalXtreme_center_rows`, G)
}

findindexc <- function(X, candidates, U_K) {
    .Call(`_causalXtreme_findindexc`, X, candidates, U_K)
}

computeRc <- function(X, candidates, U_K, M) {
    .Call(`_causalXtreme_computeRc`, X, candidates, U_K, M)
}

